### ISSUE TITLE
color variable definition

### ISSUE THREAD

**Issue by stefan-korn** [virtualidentityag/stadtKoeln-openData-frontend#26]
Custom color variables (i. e. primary color) are defined in [default.css](https://github.com/virtualidentityag/stadtKoeln-openData-frontend/blob/main/src/styles/themes/default.css).

But this does not make use of the Bootstrap sass variables. Why not override the variables in [styles.scss](https://github.com/virtualidentityag/stadtKoeln-openData-frontend/blob/main/src/styles/styles.scss#L7) like it is already done for some variables?

This way the css variables for `:root` would be generated automatically, at least for existing Bootstrap variables. And variables that Bootstrap does deviate from each other will be generated automatically too (which is not the case right now), like for example some border colors or text colors that are based on `$primary`.

And redundancies like defining `--primary` and `--primary-rgb` would be avoided.

**Comment by paulovareiro29** [comment]
Hi @stefan-korn ,
this was done this way to make life easier to implement new themes, by just overriding the theme variables in default.css.

This way we can also declare the variables as we want in darkmode, and not rely on bootstrap to generate it automatically, which in this case, would have an accessibility problem due to `#a01e28` not being accessible in dark backgrounds.
